FROM ubuntu:21.10 as developer-base
LABEL maintainer="terry.simons@gmail.com"
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y && apt install -y \
    build-essential \
    clang \
    coreutils \
    curl \
    firefox \
    git \
    git-email \
    libaio-dev \
    libbluetooth-dev \
    libbz2-dev \
    libcap-dev \
    libcap-ng-dev \
    libcurl4-gnutls-dev \
    libgtk-3-dev \
    libibverbs-dev \
    libfdt-dev \
    libfuse3* \
    libglib2.0-dev \
    libiscsi-dev \
    libjpeg8-dev \
    libkeyutils-dev \
    libncurses5-dev \
    libnfs-dev \
    libnuma-dev \
    libpixman-1-dev \
    libpython3-dev \
    librbd-dev \
    librdmacm-dev \
    libsasl2-dev \
    libsdl1.2-dev \
    libseccomp-dev \
    libslirp-dev \
    libsnappy-dev \
    libssh2-1-dev \
    libu2f* \
    libvde-dev \
    libvdeplug-dev \
    libvte-dev \
    libxen-dev \
    liblzo2-dev \
    lldb \
    multipath-tools* \
    ninja-build \
    python3 \
    python3-dev \
    python3-pip \
    python3-sphinx \
    sphinx \
    slirp \
    strace \
    sudo \
    sysfsutils \
    u2f* \
    unzip \
    valgrind \
    wget \
    xfslibs-dev \
    zlib1g-dev

FROM developer-base as opengl-base
RUN apt install -y \
    *epoxy* \
    libosmesa* \
    lib*gl*mesa* \
    libgbm* \
    libvulkan1 \
    glmemperf \
    mesa-utils \
    mesa-utils-extra \
    mesa-vulkan-drivers \
    vulkan-tools

FROM opengl-base as qemu-base
RUN apt install -y \
    aqemu \
    binutils-dev \
    libqcow* \    
    libvirt-daemon-driver-* \
    libvirglrenderer-dev \
    qemu-guest-agent \
    qemu-user \
    sparse

# For building new QEMU:
# --enable-rdma
# https://community.mellanox.com/s/article/howto-enable--verify-and-troubleshoot-rdma#jive_content_id_For_Ubuntu_Installation
RUN apt install -y \
    rdma* \
    infiniband-diags \
    libibumad* \
    ibutils \
    ibverbs-utils \
    tgt \
    targetcli* \
    istgt \
    open-iscsi \
    libiscsi*

# --enable-membarrier
RUN apt install -y \
    liburcu*

# --enable-spice
RUN apt install -y \
    spice-* \
    libspice-*

# --enable-smartcard
RUN apt install -y \
    libcacard*

# --enable-libusb
RUN apt install -y \
    libusb*

# --enable-opengl
RUN apt install -y \
    libosmesa* \
    lib*gl*mesa* \
    *epoxy* \
    libgbm*

# --enable-gluster
RUN apt install -y \
    glusterfs* \
    libgfap* \
    libgfchange* \
    libgfrpc* \
    libgfxdr* \
    libgluster* \
    nfs-*gluster \
    uwsgi*gluster*

# --enable-libssh
RUN apt install -y \
   *gcrypt*

# Not working:
# --enable-lzfse
RUN apt install -y \
    lz*

# --enable-libxml2
RUN apt install -y \
    libxml2*

# Not working:
# --enable-tcmalloc
RUN apt install -y \
    gperf*

# --enable-jemalloc
RUN apt install -y \
    libjemalloc*

# --enable-vxhs
# ERROR: User requested feature vxhs block device
#       configure was not able to find it.
#       Install libvxhs See github

# --enable-libpmem
RUN apt install -y \
    libpmem*

FROM qemu-base as developer-local

RUN apt install -y \
    emacs \
    firefox \
    # libcrypt2 \
    libgcrypt20* \
    libsdl2-* \
    libvirt-clients \
    libvirt-daemon \
    libvte* \
    nmap \
    ncat

ARG USER=developer
ENV USER=${USER}
ARG HOME=/home/${USER}
ENV HOME=${HOME}

RUN adduser --home ${HOME} --disabled-password --gecos "Developer Account" --shell /bin/bash ${USER}
# RUN usermod -a -G libvirt ${USER}
RUN usermod -a -G video ${USER}
RUN echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers


# http://ask.xmodulo.com/install-full-kernel-source-debian-ubuntu.html
# RUN git clone git://kernel.ubuntu.com/ubuntu/ubuntu-$(lsb_release --codename | cut -f2).git
# RUN sudo apt-get build-dep linux-image-$(uname -r)
# RUN git clone https://github.com/luigirizzo/netmap.git
# WORKDIR ${HOME}/netmap

# --enable-linux-io-uring  Linux io_uring support
RUN apt install -y \
    liburing-dev

# --enable-zstd
RUN apt install -y \
    libzstd-dev

# --enable-lzfse
RUN apt install -y \
    liblzf-dev

# --enable-bpf
RUN apt install -y \
    libbpf-dev \
    libbpfcc-dev

# --enable-capstone
RUN apt install -y \
    libcapstone-dev

USER ${USER}
WORKDIR ${HOME}
ARG QEMU_VERSION=6.1.0
ARG QEMU_ROOT=qemu-${QEMU_VERSION}
ARG QEMU_TARBALL=${QEMU_ROOT}.tar.bz2
ARG QEMU_PREFIX_PATH=/usr/local
ARG QEMU_CC=clang
ARG QEMU_CXX=clang++

ENV QEMU_VERSION=${QEMU_VERSION}
ENV QEMU_ROOT=${QEMU_ROOT}
ARG QEMU_TARBALL=${QEMU_TARBALL}
ARG QEMU_PREFIX_PATH=${QEMU_PREFIX_PATH}
ARG QEMU_CC=${QEMU_CC}
ARG QEMU_CXX=${QEMU_CXX}

RUN wget https://download.qemu.org/${QEMU_TARBALL}
RUN tar xvfj ${QEMU_TARBALL}

RUN pip install meson

RUN mkdir ${HOME}/${QEMU_ROOT}/build

WORKDIR ${HOME}/${QEMU_ROOT}/build
# Build with clang
RUN ../configure \
    --prefix=${QEMU_PREFIX_PATH} \
    # --cc=${QEMU_CC} \
    # --cxx=${QEMU_CXX} \
    --enable-hax \
    --enable-membarrier \
    --enable-jemalloc \
    --enable-modules \
    | grep -e ": NO$"

RUN make -j $(nproc)
RUN sudo make install

# ./configure --cc=clang --cxx=clang++ --enable-hax --enable-membarrier --enable-rbd --enable-xfsctl --enable-snappy --enable-avx2

#RUN bash configure \
#    --enable-gprof \
#    --enable-sparse \
#    --enable-profiler \
#    --enable-vte \
#    --enable-hax \
#    --enable-hvf \
#    --disable-whpx \
#    --enable-tcg-interpreter \
#    --enable-rdma \
#    --enable-membarrier \
#    --enable-spice \
#    --enable-smartcard \
#    --enable-libusb \
#    --enable-opengl \
#    --enable-gcov \
#    --enable-debug

RUN sudo apt install -y \
    *canberra*

WORKDIR ${HOME}

FROM developer-local as vscode-stage

COPY keyboard-configuration.exp ${HOME}
RUN sudo apt install -y expect
RUN expect ${HOME}/keyboard-configuration.exp

RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
RUN sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
RUN sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

RUN sudo apt install -y apt-transport-https
RUN sudo apt update
# Does not work on M1 Macs
# RUN sudo apt install -y code # or code-insiders

# Install VSCode plugins.
# COPY install-vscode-extensions.sh ${HOME}/install-vscode-extensions.sh
# RUN ${HOME}/install-vscode-extensions.sh

# Use the same VSCode settings as the host user.
# COPY vscode-settings ${HOME}/.vscode
# RUN sudo chown -R ${USER} ${HOME}/.vscode

# RUN code --list-extensions --show-versions

FROM vscode-stage as final-stage


COPY entrypoint.sh ${HOME}/entrypoint.sh
RUN sudo chmod 755 ${HOME}/entrypoint.sh
ENTRYPOINT ["/home/developer/entrypoint.sh"]

COPY healthcheck.sh ${HOME}/healthcheck.sh
RUN sudo chmod 755 ${HOME}/healthcheck.sh
HEALTHCHECK CMD ["/home/developer/healthcheck.sh"]

